// User reducer types
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const PATCH_PASSWORD = "PATCH_PASSWORD";
// Error reducer types
export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const CLEAR_ALL_ERRORS = "CLEAR_ALL_ERRORS";
// Loading reducer types
export const SET_LOADING_ACTION = "SET_LOADING_ACTION";
export const STOP_LOADING_ACTION = "STOP_LOADING_ACTION";
export const LOADING_DATA = "LOADING_DATA";
export const LOADING_WHOIS = "LOADING_WHOIS";
export const STOP_LOADING_DATA = "STOP_LOADING_DATA";
export const LOADING_FOLDER_SEARCH = "LOADING_FOLDER_SEARCH";
export const STOP_LOADING_FOLDER_SEARCH = "STOP_LOADING_FOLDER_SEARCH";
export const STOP_LOADING_WHOIS = "STOP_LOADING_WHOIS";
// Data reducer types
// Images
export const GET_BANNER_IMAGE = "GET_BANNER_IMAGE";
export const PATCH_BANNER_IMAGE = "PATCH_BANNER_IMAGE";
// Announcements
export const SET_ANNOUNCEMENTS = "SET_ANNOUNCEMENTS";
export const POST_ANNOUNCEMENT = "POST_ANNOUNCEMENT";
export const PATCH_ANNOUNCEMENT = "PATCH_ANNOUNCEMENT";
export const DELETE_ANNOUNCEMENT = "DELETE_ANNOUNCEMENT";
export const FILTER_ANNOUNCEMENTS = "FILTER_ANNOUNCEMENTS";
// Newsletters
export const SET_NEWSLETTERS = "SET_NEWSLETTERS";
export const POST_NEWSLETTER = "POST_NEWSLETTER";
export const PATCH_NEWSLETTER = "PATCH_NEWSLETTER";
export const DELETE_NEWSLETTER = "DELETE_NEWSLETTER";
// Departments
export const SET_DEPARTMENTS = "SET_DEPARTMENTS";
export const POST_DEPARTMENT = "POST_DEPARTMENT";
export const PATCH_DEPARTMENT = "PATCH_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";
// Contacts
export const SET_CONTACTS = "SET_CONTACTS";
export const POST_CONTACT = "POST_CONTACT";
export const PATCH_CONTACT = "PATCH_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const SEARCH_CONTACTS = "SEARCH_CONTACTS";
// Folders
export const SET_FOLDER = "SET_FOLDER";
export const POST_FOLDER = "POST_FOLDER";
export const PATCH_FOLDER = "PATCH_FOLDER";
export const PATCH_SUBFOLDER = "PATCH_SUBFOLDER";
export const DELETE_SUBFOLDER = "DELETE_SUBFOLDER";
export const SORT_SUBFOLDER = "SORT_SUBFOLDER";
// export const MOVE_SUBFOLDER = "MOVE_SUBFOLDER";
export const SET_NAV_PATH = "SET_NAV_PATH";
export const RESET_NAV_PATH = "RESET_NAV_PATH";
export const SET_FOLDER_SEARCH_RESULTS = "SET_FOLDER_SEARCH_RESULTS";
// Calendar
export const SET_EVENTS = "SET_EVENTS";
// Misc
export const SET_WHOIS_DATA = "SET_WHOIS_DATA";
// Data Handling
export const SET_FOLDER_ARRAY = "SET_FOLDER_ARRAY";
export const DELETE_DATA = "DELETE_DATA";
export const POST_DATA = "POST_DATA";
